--TABLES
CREATE TABLE PRODUCT(
ID INT NOT NULL,
NAME VARCHAR(100) NOT NULL,
CONSTRAINT PK_PRODUCT PRIMARY KEY (ID)
);

CREATE TABLE KARDEX(
ID INT NOT NULL,
PRODUCT_ID INT NOT NULL,
TRANSACTION_TYPE VARCHAR(50),
DETAIL VARCHAR(200),
AMOUNT NUMERIC(10,2) NOT NULL,
UNIT_VALUE NUMERIC(10,2) NOT NULL,
TOTAL_VALUE NUMERIC(10,2) NOT NULL,
CONSTRAINT PK_KARDEX PRIMARY KEY (ID),
CONSTRAINT FK_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID)
);

--SEQUENCES
CREATE SEQUENCE IF NOT EXISTS SEQ_PRODUCT INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS SEQ_KARDEX INCREMENT BY 1;
